org: faridaquino
service: notifications-service

provider:
  name: aws
  runtime: python3.12
  timeout: 29
  region: us-east-1
  stage: dev
  
  iam:
    role: arn:aws:iam::738683684819:role/LabRole

  environment:
    USERS_DEVICES: ${self:custom.usersDevices}

package:
  patterns:
    - '!node_modules/**'       # Ignorar carpeta de node
    - '!.serverless/**'        # Ignorar carpeta oculta de despliegue
    - '!venv/**'               # Ignorar entorno virtual (si tienes uno)
    - '!__pycache__/**'        # Ignorar archivos compilados de python
    - '!package-lock.json'
    - ./** # Incluir todo lo demás (tu código + librerías instaladas)
  

custom:
  usersDevices: UsersDevicesTarmaLimpia
  snsTopicName: send-push-notification-topic

  pythonRequirements:
    dockerizePip: non-linux  # Esto es VITAL para firebase-admin si estás en Windows/Mac
    layer: false

plugins:
  - serverless-python-requirements

functions:
  registrarToken:
    handler: handler.registrarToken
    events:
      - http:
          path: /registrarToken
          method: post
          cors: true

  sendPushNotification:
    handler: handler.lambda_handler
    events:
      # ESTO ES LO QUE VINCULA LA LAMBDA AL SNS
      # Serverless creará el Topic automáticamente si no existe
      - sns:
          arn: !Ref PushNotificationsTopic
          topicName: ${self:custom.snsTopicName}
  
resources:
  Resources:
    UsersDevice:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersDevices}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
      
    PushNotificationsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.snsTopicName}
        DisplayName: "Notificaciones Tarma Limpia"
    

