service: notifications-service

provider:
  name: aws
  runtime: python3.12
  timeout: 29
  region: us-east-1
  stage: dev
  iam:
    role: arn:aws:iam::738683684819:role/LabRole

  environment:
    USERS_DEVICES: ${self:custom.usersDevices}
    # Agregamos esta variable para que la lambda sepa a qué SNS enviar (si lo necesita)
    SNS_TOPIC_ARN: !Ref PushNotificationsTopic 

package:
  patterns:
    - '!node_modules/**'       
    - '!.serverless/**'        
    - '!venv/**'               
    - '!__pycache__/**'        
    - '!package-lock.json'
    - ./** # --- CORRECCIÓN AQUÍ ---
# 'custom' debe ser un bloque principal, alineado a la izquierda.
custom:
  usersDevices: UsersDevicesTarmaLimpia
  snsTopicName: send-push-notification-topic
  
  # CONFIGURACIÓN DEL PLUGIN (CRUCIAL PARA QUE FUNCIONE EL IMPORT)
  pythonRequirements:
    dockerizePip: non-linux  # Esto es VITAL para firebase-admin si estás en Windows/Mac
    layer: false             # Por ahora lo metemos todo en el zip (más fácil)

# AGREGAMOS LA SECCIÓN DE PLUGINS
plugins:
  - serverless-python-requirements

functions:
  registrarToken:
    handler: handler.registrarToken
    events:
      - http:
          path: /registrarToken
          method: post
          cors: true

  sendPushNotification:
    handler: handler.lambda_handler
    events:
      # Vinculación correcta al recurso creado abajo
      - sns:
          arn: !Ref PushNotificationsTopic
          topicName: ${self:custom.snsTopicName}
  
resources:
  Resources:
    UsersDevice:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersDevices}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
      
    # Definición explícita del Topic
    PushNotificationsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.snsTopicName}
        DisplayName: "Notificaciones Tarma Limpia"