org: faridaquino
service: api-usuarios-tarma-limpia

provider:
  name: aws
  runtime: python3.12
  timeout: 29
  region: us-east-1
  stage: dev
  
  iam:
    role: arn:aws:iam::738683684819:role/LabRole

  websocketsApiName: api-websocket-tarma-limpia-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action

  environment:
    USUARIOS_TABLE: ${self:custom.usuariosTable}
    UBICACIONES_TABLE: ${self:custom.ubicacionesTable}
    CONNECTIONS_TABLE: ${self:custom.connectionsTable}
    UBICACION_BASURERO_TABLE: ${self:custom.ubicacionBasureroTable}
    RUTAS_TABLE: RutaTarmaLimpia
package:
  patterns:
    - '!node_modules/**'       # Ignorar carpeta de node
    - '!.serverless/**'        # Ignorar carpeta oculta de despliegue
    - '!venv/**'               # Ignorar entorno virtual (si tienes uno)
    - '!__pycache__/**'        # Ignorar archivos compilados de python
    - '!package-lock.json'
    - ./** # Incluir todo lo demás (tu código + librerías instaladas)


custom:
  usuariosTable: UsuariosTarmaLimpia
  ubicacionesTable: UbicacionesTarmaLimpia
  connectionsTable: ConnectionsTarmaLimpia
  ubicacionBasureroTable: UbicacionBasureroTarmaLimpia
  
functions:

  registrarUsuario:
    handler: handler.registrarUsuario
    events:
      - http:
          path: /register
          method: post
          cors: true

  loginUsuario:
    handler: handler.loginUsuario
    events:
      - http:
          path: /login
          method: post
          cors: true

  publicarUbicacion:
    handler: handler.publicarUbicacion
    events:
      - http:
          path: /publicarUbicacion
          method: post
          cors: true
  
  obtenerRutas:
    handler: handler.getRutas
    events:
      - http:
          path: /obtenerRutas
          method: get
          cors: true

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usuariosTable}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    UbicacionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ubicacionesTable}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
